-- Hyderabad Real Estate News
-- Supabase SQL migration
--
-- Creates the `news` table used by the backend news pipeline.
-- Run this in Supabase Dashboard -> SQL Editor.

create table if not exists public.news (
    id bigint generated by default as identity primary key,

    source text,
    title text not null,
    url text,
    raw_content text,
    image_url text,
    classifier text,

    created_at timestamptz not null default now()
);

-- Helpful indexes for the backend/frontend.
create index if not exists news_classifier_idx
    on public.news (classifier);

create index if not exists news_created_at_idx
    on public.news (created_at desc);

-- Prevent the same source URL from being stored repeatedly.
-- Only applies when a URL is present.
create unique index if not exists news_url_unique_idx
    on public.news (url)
    where url is not null;

-- Enable Row Level Security.
alter table public.news enable row level security;

-- Public/read access for the React frontend.
-- The backend uses the service key to insert generated news.
drop policy if exists "Public can read published news" on public.news;

create policy "Public can read news"
on public.news
for select
to anon, authenticated
using (true);

-- Backend/service-role inserts bypass RLS automatically.
-- No public insert/update/delete policy is created intentionally.
